# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.64983103 0.5463332  0.52505735]
  [0.58807853 0.37598616 0.57702706]
  [0.64461657 0.42429126 0.57459771]]

 [[0.28264448 0.44851776 0.25421376]
  [0.56153608 0.31885344 0.21641331]
  [0.30639606 0.84187168 0.08524465]]

 [[0.9338354  0.47544513 0.14302627]
  [0.75557294 0.41306566 0.81720387]
  [0.23014423 0.24250183 0.18099684]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.ones((3,3))
print("Checkerboard pattern:")

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
a= np.random.rand(5,5)
a

array([[0.93789418, 0.22958831, 0.9842685 , 0.63114167, 0.83856461],
       [0.22525787, 0.53886836, 0.10245205, 0.34968212, 0.54263209],
       [0.77960837, 0.82342739, 0.42515378, 0.33936155, 0.83193343],
       [0.18400465, 0.35233549, 0.57852317, 0.74625157, 0.02267031],
       [0.57247698, 0.56507935, 0.58649654, 0.13362669, 0.12914205]])

# 5.  How to find common values between two arrays?

In [8]:
a = (1, 2, 4, 5, 6, 11, 22, 33)
b = (2, 4, 5, 6, 7, 8, 33)
list(set(a).intersection(set(b)))

[33, 2, 4, 5, 6]

# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)

Yestraday:  2020-07-27


In [11]:
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Tomorrow:  2020-07-29


In [12]:
today     = np.datetime64('today', 'D')
print("Today: ",today)

Today:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [23]:
a = np.random.rand(1)
b = np.random.rand(3)

a == b

array([False, False, False])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [3]:
import numpy as np
vector = np.random.random(10)
vector[vector.argmax()] = 0
print("Replaced Maximum value by 0:")
print(vector)

Replaced Maximum value by 0:
[0.85971938 0.82952531 0.39122406 0.38100221 0.58867576 0.7606351
 0.         0.23105304 0.47441634 0.09935991]


# 9. How to print all the values of an array?

In [46]:
arr= np.random.rand(5)
for one_ele in arr:
    print(one_ele)

0.9487150950559855
0.09292851312316464
0.3352168750287381
0.8858155717466314
0.7181877802235287


# 10.Subtract the mean of each row of a matrix

In [55]:
mat = np.random.rand(3, 3)
mat = mat - mat.mean()
mat

array([[-0.06514845, -0.03235328, -0.25571015],
       [ 0.47429401,  0.42925804,  0.33734634],
       [-0.40306527, -0.28932312, -0.19529812]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [4]:
vector = np.random.rand(10)
vector.sort()
vector

array([0.07846697, 0.09788951, 0.25141626, 0.32095417, 0.51602344,
       0.76158084, 0.78060412, 0.8500185 , 0.96340617, 0.99977833])

# 12.How to get the diagonal of a dot product?

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,6,3],[8,5,8],[7,5,3]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 6 3]
 [8 5 8]
 [7 5 3]]


In [10]:
c = a.dot(b)
c

array([[ 46,  31,  28],
       [118,  79,  70],
       [190, 127, 112]])

In [18]:
c.diagonal()

array([ 46,  79, 112])

# 13.How to find the most frequent value in an array?

In [20]:
from scipy import stats

In [21]:
arr = [1,2,3,1,2,3,5,6,2,3,6,2,3,5,2,3,3,2,3,4,6,2,3]
stats.mode(arr)[0][0]

3

# 14.How to get the n largest values of an array

In [24]:
a = np.random.rand(1000)
a.sort()
top = 5
top_value = a[:top]
top_value

array([0.00129735, 0.00159196, 0.00337619, 0.00433605, 0.00467168])

In [25]:
top_value.size

5

# 15.How to create a record array from a regular array?